/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpenInstagramEmbed {
        "count": number;
        "datasource": string;
    }
}
declare global {
    interface HTMLOpenInstagramEmbedElement extends Components.OpenInstagramEmbed, HTMLStencilElement {
    }
    var HTMLOpenInstagramEmbedElement: {
        prototype: HTMLOpenInstagramEmbedElement;
        new (): HTMLOpenInstagramEmbedElement;
    };
    interface HTMLElementTagNameMap {
        "open-instagram-embed": HTMLOpenInstagramEmbedElement;
    }
}
declare namespace LocalJSX {
    interface OpenInstagramEmbed {
        "count"?: number;
        "datasource"?: string;
    }
    interface IntrinsicElements {
        "open-instagram-embed": OpenInstagramEmbed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "open-instagram-embed": LocalJSX.OpenInstagramEmbed & JSXBase.HTMLAttributes<HTMLOpenInstagramEmbedElement>;
        }
    }
}
