/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface OpenInstagramEmbed {
        "count": number;
        "datasource": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLOpenInstagramEmbedElement extends Components.OpenInstagramEmbed, HTMLStencilElement {
    }
    var HTMLOpenInstagramEmbedElement: {
        prototype: HTMLOpenInstagramEmbedElement;
        new (): HTMLOpenInstagramEmbedElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "open-instagram-embed": HTMLOpenInstagramEmbedElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface OpenInstagramEmbed {
        "count"?: number;
        "datasource"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "open-instagram-embed": OpenInstagramEmbed;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "open-instagram-embed": LocalJSX.OpenInstagramEmbed & JSXBase.HTMLAttributes<HTMLOpenInstagramEmbedElement>;
        }
    }
}
